export enum CommunityCategory {
  PERIOD_CRAMPS = 'PERIOD_CRAMPS',
  BIRTH_CONTROL = 'BIRTH_CONTROL',
  MENTAL_HEALTH_MOOD = 'MENTAL_HEALTH_MOOD',
  RELATIONSHIP = 'RELATIONSHIP',
  PREGNANCY = 'PREGNANCY',
  MARRIAGE_LIFE = 'MARRIAGE_LIFE',
}
